### ISSUE TITLE
missing plugin @vueuse/core 

### ISSUE THREAD

**Issue by mohamad-supangat** [vitepress-custom/vitepress-custom#7]
package manager: pnpm
vitepress-custom: @vitepress-custom/vitepress-custom-cli 0.0.5

reproduction:
- pnpm add -g @vitepress-custom/vitepress-custom-cli
- vitepress-custom-cli init
- pnpm install 
- pnpm dev

fixing:
- pnpm add @vueuse/core

**Comment by huyikai** [comment]
Thank you for providing issue. But the code was refactored for a variety of reasons. The new address is at https://github.com/huyikai/vitepress-helper. The current organization will be closed soon.
